[tox]
envlist = integration
skipsdist = true

[testenv:integration]
skip_install = true
allowlist_externals = make
passenv =
    CHARM_PATH
    BASE
    SPREAD_JOB
commands =
    make integration-execution ARGS="--base={env:BASE:24.04} {posargs}"
