[tox]
skipsdist = True
envlist = lint, format, unit, integration

[testenv]
setenv =
    PYTHONPATH={toxinidir}/src
    PYTHONBREAKPOINT=ipdb.set_trace

[testenv:lint]
description = Lint the code
deps =
    ruff
commands =
    ruff check {toxinidir}/src {toxinidir}/tests
    ruff format --check {toxinidir}/src {toxinidir}/tests

[testenv:format]
description = Auto-format the code
deps =
    ruff
commands =
    ruff check --fix {toxinidir}/src {toxinidir}/tests
    ruff format {toxinidir}/src {toxinidir}/tests

[testenv:unit]
description = Run unit tests
deps =
    pytest
    ops[testing]>=2.0
    -r{toxinidir}/requirements.txt
commands = pytest --tb native --show-capture=no --log-cli-level=INFO -s -W error {posargs} {toxinidir}/tests/unit

[testenv:integration]
description = Run integration tests
deps =
    pytest
    pytest-operator
    websockets<14
    -r{toxinidir}/requirements.txt
commands = pytest --tb native --show-capture=no --log-cli-level=INFO -s --disable-warnings --model-config tests/data/model-config.yaml {posargs} {toxinidir}/tests/integration
