name: Integration Tests

on:
  pull_request:

jobs:
  integration-test:
    permissions:
      actions: read
      contents: read
      packages: write
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@7e08ea41eadd61b4bc14ce408c660699deed6567  # v0.0.1-alpha.6
    with:
      working-directory: .
