name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@7e08ea41eadd61b4bc14ce408c660699deed6567  # v0.0.1-alpha.6
    permissions:
      actions: read
      contents: write
    with:
      channel: latest/edge
      integration-workflow-name: integration-test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
