name: SBOM and secscan

on:
  workflow_dispatch:
  schedule:
    # Run on the 10th of April and October, aligned to the Canonical release cycle.
    - cron: "0 0 10 4,10 *"

permissions: {}

jobs:
  scan:
    name: SBOM and secscan
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: sbomber
        uses: canonical/sbomber/.github/actions/run@cf7a76e810497ec932e8285b2c9d6b373d225e79  # main -- the sbomber-ref input below should match
        with:
          manifest: ${{ github.workspace }}/.github/.sbomber-manifest.yaml
          artifact-name: secscan-report-upload
          sbomber-ref: cf7a76e810497ec932e8285b2c9d6b373d225e79  # should match the ref in 'uses' above
