name: Spread Integration Tests
on: [pull_request]

permissions: {}

jobs:
  build:
    name: Build charm
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          persist-credentials: false

      - name: Set up runner
        run: |
          sudo snap install --classic concierge
          sudo concierge prepare --trace -p machine

      - name: Build charm
        run: charmcraft pack

      - name: Upload charm artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: charm
          path: ubuntu_*.charm
          if-no-files-found: error

  spread:
    name: base ${{ matrix.base }} / juju ${{ matrix.juju }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["20.04", "22.04", "24.04", "26.04"]
        juju: ["3.6", "4.0"]
        exclude:
          # juju 4 no longer supports 20.04.
          - base: "20.04"
            juju: "4.0"
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7
        with:
          persist-credentials: false

      - name: Download charm artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: charm

      - name: Set up runner
        run: |
          sudo snap install --classic concierge
          sudo concierge prepare --trace -p machine

      - name: Run spread
        env:
          CI: "true"
        run: |
          juju_slug="${{ matrix.juju }}"
          juju_slug="${juju_slug//./_}"
          charmcraft.spread -v "lxd:ubuntu-24.04:tests/spread/integration/ubuntu-${{ matrix.base }}:juju_${juju_slug}"

      - name: Tear down on failure
        if: failure()
        run: sudo concierge restore --trace
