name: Spread Integration Tests
on: [pull_request]

permissions: {}

jobs:
  spread:
    name: Spread integration test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Read charmcraft version file
        id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT

      - name: Build charm
        env:
          CHARMCRAFT_CHANNEL: ${{ steps.charmcraft.outputs.channel }}
        run: |
          sudo snap install --classic charmcraft
          charmcraft pack --channel "$CHARMCRAFT_CHANNEL"

      - name: Install spread
        run: sudo snap install spread

      - name: Run spread
        env:
          CI: "true"
        run: spread -v lxd:ubuntu-24.04

      - name: Discard LXD instance on failure
        if: failure()
        run: spread -v lxd:ubuntu-24.04 discard
