name: TIOBE

on:
  workflow_dispatch:
  schedule:
    - cron: '38 2 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0

        # We could store the coverage report from the regular run, but this is cheap to do
        # and keeps this isolated.
      - name: Generate coverage report
        run: |
          pip install coverage pytest -r requirements.txt --break-system-packages
          PYTHONPATH=src coverage run --source=src -m pytest tests/unit
          mkdir -p .report
          coverage xml -o .report/coverage.xml

        # Note that these are dependencies for the tools that the TIOBE action will run,
        # which is done in the global environment, rather than a venv, as we do with the
        # unit tests.
      - name: Install TIOBE and project dependencies
        run: |
          pip install flake8 pylint -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@016a4d79f3027fe7b4a2901619a58c745ab7cadf  # v3.10.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: charm-ubuntu
          installTics: true
