name: TIOBE

on:
  workflow_dispatch:
  schedule:
    - cron: '38 2 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

        # We could store the coverage report from the regular run, but this is cheap to do
        # and keeps this isolated.
      - name: Generate coverage report
        run: |
          uv run --locked --group unit --group coverage coverage run --source=src -m pytest tests/unit
          mkdir .report
          uv run --locked --group unit --group coverage coverage xml -o .report/coverage.xml

        # Note that these are dependencies for the tools that the TIOBE action will run,
        # which is done in the global environment, rather than a venv, as we do with the
        # unit tests.
      - name: Install TIOBE and project dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes > requirements.txt
          pip install flake8 pylint -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@333078bc527399e5916a166bd1a3a788be5a01a9  # v3.12.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: charm-ubuntu
          installTics: true
